#string methods
str=input()
print(str.isalnum())
print(str.isalpha())
print(str.isnumeric())
print(str.isascii())
print(str.islower())
print(str.isupper())
print(str.istitle())
print(str.isdigit())
