name=input("enter your name")
sub1=int(input())
sub2=int(input())
sub3=int(input())
sub4=int(input())
print(f"hello {name} your total marks {sub1+sub2+sub3+sub4} and your average is {(sub1+sub2+sub3+sub4)/4}")
